//
//  ShareableReportCard.swift
//  Spendora
//

import SwiftUI

struct ShareableReportCard: View {
    let totalMonthly: Double
    let totalYearly: Double
    let subscriptionCount: Int
    let topCategory: String
    let topCategoryAmount: Double
    
    var body: some View {
        VStack(spacing: 24) {
            Spacer()
            
            Image(systemName: "creditcard.and.123")
                .font(.system(size: 50))
                .foregroundStyle(Color.primaryGradient)
            
            Text("My Subscription Report")
                .font(.title2)
                .fontWeight(.bold)
            
            Text(Date().formatted(date: .abbreviated, time: .omitted))
                .font(.caption)
                .foregroundColor(.secondary)
            
            Divider()
                .padding(.horizontal)
            
            VStack(spacing: 16) {
                StatCard(
                    icon: "dollarsign.circle.fill",
                    title: "Monthly Spending",
                    value: CurrencyManager.shared.format(totalMonthly),
                    color: Color.brandPrimary
                )
                
                StatCard(
                    icon: "calendar",
                    title: "Yearly Spending",
                    value: CurrencyManager.shared.format(totalYearly),
                    color: Color.brandSecondary
                )
                
                StatCard(
                    icon: "number.circle.fill",
                    title: "Active Subscriptions",
                    value: "\(subscriptionCount)",
                    color: .green
                )
                
                if topCategory != "None" {
                    StatCard(
                        icon: "chart.pie.fill",
                        title: "Top Category",
                        value: topCategory,
                        subtitle: CurrencyManager.shared.format(topCategoryAmount),
                        color: .orange
                    )
                }
            }
            .padding()
            
            Text("Generated by Spendora")
                .font(.caption2)
                .foregroundColor(.secondary)
            
            Spacer()
        }
        .padding()
        .frame(width: 350, height: 550)
        .background(Color(.systemBackground))
        .cornerRadius(32)
        .shadow(color: .black.opacity(0.1), radius: 20)
    }
}
