//
//  ShareableReportCard.swift
//  Spendora
//

import SwiftUI

struct ShareableReportCard: View {
    let totalMonthly: Double
    let totalYearly: Double
    let subscriptionCount: Int
    let topCategory: String
    let topCategoryAmount: Double
    
    var body: some View {
        VStack(spacing: 24) {
            Spacer()
            
            // Premium Icon with gradient
            ZStack {
                Circle()
                    .fill(
                        LinearGradient(
                            colors: [.brandPrimary.opacity(0.08), .brandSecondary.opacity(0.03)],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .frame(width: 80, height: 80)
                
                Image(systemName: "creditcard.and.123")
                    .font(.system(size: 40, weight: .medium))
                    .foregroundStyle(
                        LinearGradient(
                            colors: [.brandPrimary, .brandSecondary],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
            }
            
            Text("My Subscription Report")
                .font(.system(.title2, design: .rounded))
                .fontWeight(.bold)
            
            Text(Date().formatted(date: .abbreviated, time: .omitted))
                .font(.system(.caption, design: .rounded))
                .foregroundColor(.secondary)
            
            Divider()
                .padding(.horizontal)
            
            VStack(spacing: 16) {
                PremiumReportStatCard(
                    icon: "dollarsign.circle.fill",
                    title: "Monthly Spending",
                    value: CurrencyManager.shared.format(totalMonthly),
                    color: .brandPrimary
                )
                
                PremiumReportStatCard(
                    icon: "calendar",
                    title: "Yearly Spending",
                    value: CurrencyManager.shared.format(totalYearly),
                    color: .brandSecondary
                )
                
                PremiumReportStatCard(
                    icon: "number.circle.fill",
                    title: "Active Subscriptions",
                    value: "\(subscriptionCount)",
                    color: .green
                )
                
                if topCategory != "None" {
                    PremiumReportStatCard(
                        icon: "chart.pie.fill",
                        title: "Top Category",
                        value: topCategory,
                        subtitle: CurrencyManager.shared.format(topCategoryAmount),
                        color: .orange
                    )
                }
            }
            .padding(.horizontal, 8)
            
            Text("Generated by Spendora")
                .font(.system(.caption2, design: .rounded))
                .foregroundColor(.secondary)
            
            Spacer()
        }
        .padding()
        .frame(width: 350, height: 550)
        .background(
            LinearGradient(
                colors: [Color(.systemBackground), Color(.systemBackground)],
                startPoint: .top,
                endPoint: .bottom
            )
        )
        .cornerRadius(32)
        .shadow(color: .black.opacity(0.1), radius: 20, x: 0, y: 8)
    }
}

// MARK: - Premium Report Stat Card
struct PremiumReportStatCard: View {
    let icon: String
    let title: String
    let value: String
    var subtitle: String? = nil
    let color: Color
    
    var body: some View {
        HStack(spacing: 14) {
            ZStack {
                Circle()
                    .fill(color.opacity(0.12))
                    .frame(width: 36, height: 36)
                
                Image(systemName: icon)
                    .font(.title3)
                    .foregroundColor(color)
            }
            
            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.system(.caption, design: .rounded))
                    .foregroundColor(.secondary)
                
                Text(value)
                    .font(.system(.headline, design: .rounded))
                    .fontWeight(.bold)
                
                if let subtitle = subtitle {
                    Text(subtitle)
                        .font(.system(.caption2, design: .rounded))
                        .foregroundColor(.secondary)
                }
            }
            
            Spacer()
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 10)
        .background(
            RoundedRectangle(cornerRadius: 12)
                .fill(Color(.secondarySystemBackground))
                .shadow(color: Color.black.opacity(0.02), radius: 4, x: 0, y: 2)
        )
    }
}
