//
//  ShareableChallenges.swift
//  Spendora
//

import SwiftUI

struct ShareableChallenges: View {
    let percentage: Int
    let challenges: [Challenge]
    
    var body: some View {
        VStack(spacing: 24) {
            Spacer()
            
            Text("My Subscription Challenges")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundColor(.primary)
            
            Text("\(percentage)% Complete")
                .font(.largeTitle)
                .fontWeight(.bold)
                .foregroundStyle(
                    LinearGradient(
                        colors: [Color(hex: "#FF6B6B"), Color(hex: "#4ECDC4")],
                        startPoint: .leading,
                        endPoint: .trailing
                    )
                )
            
            VStack(spacing: 12) {
                ForEach(challenges.prefix(4)) { challenge in
                    HStack {
                        Image(systemName: challenge.isCompleted ? "checkmark.circle.fill" : "circle")
                            .foregroundColor(challenge.isCompleted ? .green : .gray)
                        
                        Text(challenge.title)
                            .font(.body)
                            .foregroundColor(challenge.isCompleted ? .primary : .secondary)
                        
                        Spacer()
                    }
                }
            }
            .padding()
            .background(Color(.secondarySystemBackground))
            .cornerRadius(16)
            
            Text("Generated by Spendora")
                .font(.caption2)
                .foregroundColor(.secondary)
            
            Spacer()
        }
        .padding()
        .frame(width: 350, height: 420)
        .background(Color(.systemBackground))
    }
}
