//
//  ShareableYearlyReport.swift
//  Spendora
//

import SwiftUI

struct ShareableYearlyReport: View {
    let year: Int
    let totalYearly: Double
    let averageMonthly: Double
    let topCategory: String
    
    var body: some View {
        VStack(spacing: 24) {
            Spacer()
            
            Text("\(year) Spending Report")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundColor(.primary)
            
            Image(systemName: "creditcard.and.123")
                .font(.system(size: 50))
                .foregroundStyle(Color.primaryGradient)
            
            VStack(spacing: 16) {
                HStack {
                    Text("Total Yearly")
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Spacer()
                    Text(CurrencyManager.shared.format(totalYearly))
                        .font(.title3)
                        .fontWeight(.bold)
                }
                
                HStack {
                    Text("Monthly Average")
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Spacer()
                    Text(CurrencyManager.shared.format(averageMonthly))
                        .font(.title3)
                        .fontWeight(.bold)
                }
                
                if topCategory != "None" {
                    HStack {
                        Text("Top Category")
                            .font(.caption)
                            .foregroundColor(.secondary)
                        Spacer()
                        Text(topCategory)
                            .font(.title3)
                            .fontWeight(.bold)
                    }
                }
            }
            .padding()
            .background(Color(.secondarySystemBackground))
            .cornerRadius(16)
            
            Text("Generated by Spendora")
                .font(.caption2)
                .foregroundColor(.secondary)
            
            Spacer()
        }
        .padding()
        .frame(width: 350, height: 450)
        .background(Color(.systemBackground))
    }
}
