//
//  ShareableScoreCard.swift
//  Spendora
//

import SwiftUI

struct ShareableScoreCard: View {
    let score: Int
    let count: Int
    let total: Double
    
    var body: some View {
        VStack(spacing: 24) {
            Spacer()
            
            Text("My Savings Score")
                .font(.title2)
                .fontWeight(.bold)
            
            ZStack {
                Circle()
                    .stroke(Color.gray.opacity(0.2), lineWidth: 12)
                    .frame(width: 120, height: 120)
                
                Circle()
                    .trim(from: 0, to: CGFloat(score) / 100)
                    .stroke(
                        LinearGradient(
                            colors: [Color(hex: "#FF6B6B"), Color(hex: "#4ECDC4")],
                            startPoint: .top,
                            endPoint: .bottom
                        ),
                        style: StrokeStyle(
                            lineWidth: 12,
                            lineCap: .round
                        )
                    )
                    .frame(width: 120, height: 120)
                    .rotationEffect(.degrees(-90))
                
                VStack(spacing: 4) {
                    Text("\(score)")
                        .font(.system(size: 36, weight: .bold))
                    
                    Text("Score")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
            
            VStack(spacing: 8) {
                Label(
                    "\(count) subscriptions",
                    systemImage: "number.circle.fill"
                )
                .foregroundColor(.secondary)
                
                Label(
                    CurrencyManager.shared.format(total) + "/month",
                    systemImage: "dollarsign.circle.fill"
                )
                .foregroundColor(.secondary)
            }
            
            Text("Generated by Spendora")
                .font(.caption2)
                .foregroundColor(.secondary)
            
            Spacer()
        }
        .padding()
        .frame(width: 350, height: 400)
        .background(Color(.systemBackground))
    }
}
