//
//  ShareableYearlyReport.swift
//

import SwiftUI


// MARK: - ShareableYearlyReport

/**
 `ShareableYearlyReport` is a struct that manages core data, layout, or business logic within Spendora.
 
 ## Features
 - Serves as a key component for shareableyearlyreport handling
 - Adheres to Swift single responsibility principles
 - Integrates with SwiftUI reactive state updates
 
 ## Data Flow
 Properties in `ShareableYearlyReport` are initialized or updated reactively based on user interaction
 and service callbacks.
 
 - Important: Always verify state bindings before executing main thread actions.
 - Note: Part of the Spendora architecture.
 - SeeAlso: `SpendoraApp`
 */
struct ShareableYearlyReport: View {

    // MARK: - Properties

    let year: Int  // year property
    let totalYearly: Double  // totalYearly property
    let averageMonthly: Double  // averageMonthly property
    let topCategory: String  // topCategory property
    

    // MARK: - Body

    /// Main SwiftUI layout body property.
    var body: some View {
        VStack(spacing: 24) {
            Spacer()
            
            Text("\(year) Spending Report")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundColor(.primary)
            
            Image(systemName: "creditcard.and.123")
                .font(.system(size: 50))
                .foregroundStyle(
                    LinearGradient(
                        colors: [Color(hex: "#FF6B6B"), Color(hex: "#4ECDC4")],
                        startPoint: .leading,
                        endPoint: .trailing
                    )
                )
            
            VStack(spacing: 16) {
                HStack {
                    Text("Total Yearly")
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Spacer()
                    Text(CurrencyManager.shared.format(totalYearly))
                        .font(.title3)
                        .fontWeight(.bold)
                }
                
                HStack {
                    Text("Monthly Average")
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Spacer()
                    Text(CurrencyManager.shared.format(averageMonthly))
                        .font(.title3)
                        .fontWeight(.bold)
                }
                
                if topCategory != "None" {
                    HStack {
                        Text("Top Category")
                            .font(.caption)
                            .foregroundColor(.secondary)
                        Spacer()
                        Text(topCategory)
                            .font(.title3)
                            .fontWeight(.bold)
                    }
                }
            }
            .padding()
            .background(Color(.secondarySystemBackground))
            .cornerRadius(16)
            
            Text("Generated by Spendora")
                .font(.caption2)
                .foregroundColor(.secondary)
            
            Spacer()
        }
        .padding()
        .frame(width: 350, height: 450)
        .background(Color(.systemBackground))
    }
}
